name: License checker
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: npm ci
    - name: test code
      run: sh ./scripts/license-checker.sh
