name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        apt-get -y update
        apt-get -y install jq
        echo '{"name":"value"}' > hoge.json
        npm ci
        cat hoge.json | jq .name
        
      env:
        CI: true
